"""
config.py — Single source of truth for ALL hyperparameters.
All other modules import from here; never hardcode values elsewhere.

Tuned for: Direct GPU access (T4 / L4 / A100), ~150M param model, 3B tokens.
"""

import os
import torch

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_DIR     = os.path.dirname(os.path.abspath(__file__))
DATA_CACHE_DIR  = os.environ.get("DATA_CACHE_DIR", os.path.join(PROJECT_DIR, "data_cache"))
CHECKPOINT_DIR  = os.path.join(PROJECT_DIR, "checkpoints")
EVAL_OUTPUT_DIR = os.path.join(PROJECT_DIR, "eval_outputs")
FINAL_MODEL_DIR = os.path.join(PROJECT_DIR, "final_model")

# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------
HF_DATASET_ID = "bigcode/the-stack-dedup"
HF_DATA_DIR   = "data/python"
HF_SPLIT      = "train"

# ---------------------------------------------------------------------------
# Tokeniser
# ---------------------------------------------------------------------------
TOKENIZER_ID   = "bigcode/starcoder2-3b"
CONTEXT_LENGTH = 1024      # token block size (fixed, no padding)

# ---------------------------------------------------------------------------
# Quality-filter thresholds
# ---------------------------------------------------------------------------
FILTER_MIN_CHARS       = 200
FILTER_MAX_CHARS       = 80_000
FILTER_MIN_LINES       = 8
FILTER_MIN_AVG_LINE    = 10
FILTER_MAX_AVG_LINE    = 200
FILTER_MIN_ALPHA_RATIO = 0.20
FILTER_AUTOGEN_MARKERS = [
    "auto-generated",
    "do not edit",
    "generated by",
    "pb2.py",          # protobuf generated files
]

# ---------------------------------------------------------------------------
# Model architecture  (GPT-2 style, ~150M params)
# ---------------------------------------------------------------------------
VOCAB_SIZE  = 49152
N_POSITIONS = 1024
N_EMBD      = 768
N_LAYER     = 12
N_HEAD      = 12
N_INNER     = 3072    # 4 × n_embd
RESID_PDROP = 0.0
EMBD_PDROP  = 0.0
ATTN_PDROP  = 0.0
ACTIVATION  = "gelu_new"

# ---------------------------------------------------------------------------
# Data pipeline
# ---------------------------------------------------------------------------
TARGET_TOKENS         = 3_000_000_000   # 3 billion tokens
VAL_FRACTION          = 0.005           # 99.5 / 0.5 train/val split
DATA_SEED             = 42
PROGRESS_EVERY_CHUNKS = 100_000         # log progress every N chunks

# ---------------------------------------------------------------------------
# Training  (auto-detect BF16 vs FP16 based on hardware)
# ---------------------------------------------------------------------------
PER_DEVICE_BATCH = 4             # micro-batch per step
GRAD_ACCUM_STEPS = 32            # effective batch = 4 × 32 = 128 seqs = 131,072 tokens/step
EFFECTIVE_BATCH  = PER_DEVICE_BATCH * GRAD_ACCUM_STEPS

LR_INIT      = 3e-4
LR_MIN       = 3e-5
BETAS        = (0.9, 0.95)
WEIGHT_DECAY = 0.1               # only for 2D+ params, excluding LN and embeddings
EPS          = 1e-6
GRAD_CLIP    = 1.0

WARMUP_STEPS = 2000              # linear warmup
MAX_STEPS    = 35_390            # ≈ 3B tokens ÷ 131,072 tokens/step (with GRAD_ACCUM=32)


def _detect_dtype() -> str:
    """Auto-detect best mixed-precision dtype. BF16 on Ampere+, else FP16."""
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported():
        return "bfloat16"
    return "float16"


DTYPE = _detect_dtype()          # FP16 + GradScaler on T4; BF16 (no scaler) on A100/L4

# ---------------------------------------------------------------------------
# Checkpointing
# ---------------------------------------------------------------------------
SAVE_EVERY_STEPS        = 2_500                             # ~164M tokens between saves
KEEP_LAST_N_CHECKPOINTS = 999_999                          # keep all checkpoints
PERMANENT_CHECKPOINTS   = {2500, 5000, 10000, 20000, 25000, 30000, 35390}

# ---------------------------------------------------------------------------
# Evaluation (runs at every checkpoint)
# ---------------------------------------------------------------------------
EVAL_PROMPTS = [
    'def fibonacci(n):\n    """Return nth Fibonacci number."""\n',
    'def is_palindrome(s: str) -> bool:\n    """Check if string is palindrome."""\n',
    'def two_sum(nums, target):\n    """Find two indices that sum to target."""\n',
    'class Stack:\n    """LIFO stack implementation."""\n    def __init__(self):\n',
    "def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n",
]
GEN_MAX_NEW_TOKENS = 600
GEN_TEMPERATURE    = 0.7
GEN_TOP_P          = 0.95
GEN_TOP_K          = 50
GEN_DO_SAMPLE      = True
GEN_REPETITION_PEN = 1.1

# ---------------------------------------------------------------------------
# SFT Configuration
# ---------------------------------------------------------------------------
SFT_DATASET_ID    = "iamtarun/python_code_instructions_18k_alpaca"
SFT_VAL_FRACTION  = 0.05          # 95% train / 5% val
SFT_LR            = 1e-5          # 10× lower than pre-training
SFT_LR_MIN        = 1e-6
SFT_WARMUP_STEPS  = 100
SFT_EPOCHS        = 3
SFT_BATCH_SIZE    = 2             # micro-batch (150M model is larger)
SFT_GRAD_ACCUM    = 16            # effective batch = 32
SFT_MAX_SEQ_LEN   = 512
SFT_GRAD_CLIP     = 1.0
SFT_WEIGHT_DECAY  = 0.01
SFT_BETAS         = (0.9, 0.95)
SFT_EPS           = 1e-6
SFT_SAVE_EVERY    = 500
SFT_LOG_EVERY     = 25
SFT_EVAL_EVERY    = 500

SFT_INSTRUCTION_PROMPTS = [
    "### Instruction:\nWrite a Python function that takes a list of numbers and returns the largest one.\n\n### Response:\n",
    "### Instruction:\nWrite a Python function to reverse a string.\n\n### Response:\n",
    "### Instruction:\nWrite a Python function to check if a number is prime.\n\n### Response:\n",
    "### Instruction:\nWrite a Python class that represents a simple calculator with add, subtract, multiply, and divide methods.\n\n### Response:\n",
    "### Instruction:\nWrite a Python function that takes a list of strings and returns only those that are palindromes.\n\n### Response:\n",
]

# ---------------------------------------------------------------------------
# WandB
# ---------------------------------------------------------------------------
WANDB_PROJECT   = "codegen-150m"
WANDB_RUN_NAME  = "scratch-150m-3b-tokens"
LOG_EVERY_STEPS = 100
# Set WANDB_API_KEY environment variable before running, e.g.:
#   export WANDB_API_KEY=your_key_here
# Or pass it via: wandb login --relogin
WANDB_API_KEY   = os.environ.get("WANDB_API_KEY", "")
