"""
Main configuration file for the project.

Keeps dataset settings, model parameters, training hyperparameters,
checkpointing and evaluation settings in one place so other modules
can simply import from here.
"""

import os


# Project paths
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_CACHE_DIR = os.path.join(PROJECT_DIR, "data_cache")   # cached token chunks
CHECKPOINT_DIR = os.path.join(PROJECT_DIR, "checkpoints")
EVAL_OUTPUT_DIR = os.path.join(PROJECT_DIR, "eval_outputs")
FINAL_MODEL_DIR = os.path.join(PROJECT_DIR, "final_model")


# Dataset setup
HF_DATASET_ID = "bigcode/the-stack-dedup"
HF_DATA_DIR = "data/python"
HF_SPLIT = "train"


# Tokenizer settings
TOKENIZER_ID = "bigcode/starcoder2-3b"
CONTEXT_LENGTH = 1024      # training context length


# Quality filtering thresholds
FILTER_MIN_CHARS = 200
FILTER_MAX_CHARS = 80_000

FILTER_MIN_LINES = 8
FILTER_MIN_AVG_LINE = 10
FILTER_MAX_AVG_LINE = 200

FILTER_MIN_ALPHA_RATIO = 0.20

FILTER_AUTOGEN_MARKERS = [
    "auto-generated",
    "do not edit",
    "generated by",
    "pb2.py",
]


# GPT-style model (~150M params)
VOCAB_SIZE = 49152
N_POSITIONS = 1024

N_EMBD = 960
N_LAYER = 16
N_HEAD = 16
N_INNER = 3840     # feedforward hidden size

RESID_PDROP = 0.0
EMBD_PDROP = 0.0
ATTN_PDROP = 0.0

ACTIVATION = "gelu_new"


# Data pipeline settings
TARGET_TOKENS = 3_000_000_000

VAL_FRACTION = 0.005
DATA_SEED = 42

PROGRESS_EVERY_CHUNKS = 100_000


# Training setup
# Reduced batch size for 16GB VRAM and used accumulation
# to keep the effective batch large enough.
PER_DEVICE_BATCH = 1
GRAD_ACCUM_STEPS = 60

EFFECTIVE_BATCH = PER_DEVICE_BATCH * GRAD_ACCUM_STEPS


LR_INIT = 3e-4
LR_MIN = 3e-5

BETAS = (0.9, 0.95)
WEIGHT_DECAY = 0.1
EPS = 1e-8

GRAD_CLIP = 1.0

WARMUP_STEPS = 2000
MAX_STEPS = 48_828

DTYPE = "bfloat16"     # supported natively on RTX 4060


# Checkpoint settings
SAVE_EVERY_STEPS = 5_000
KEEP_LAST_N_CHECKPOINTS = 999_999

PERMANENT_CHECKPOINTS = {
    2000,
    8000,
    16000
}


# Evaluation prompts
EVAL_PROMPTS = [
    'def fibonacci(n):\n    """Return nth Fibonacci number."""\n',

    'def is_palindrome(s: str) -> bool:\n'
    '    """Check if string is palindrome."""\n',

    'def two_sum(nums, target):\n'
    '    """Find two indices that sum to target."""\n',

    'class Stack:\n'
    '    """LIFO stack implementation."""\n'
    '    def __init__(self):\n',

    "def binary_search(arr, target):\n"
    "    left, right = 0, len(arr) - 1\n",
]


GEN_MAX_NEW_TOKENS = 600
GEN_TEMPERATURE = 0.7

GEN_TOP_P = 0.95
GEN_TOP_K = 50

GEN_DO_SAMPLE = True
GEN_REPETITION_PEN = 1.3


# Experiment tracking
WANDB_PROJECT = "codegen-150m"
WANDB_RUN_NAME = "rtx4060-3b-tokens"

LOG_EVERY_STEPS = 100
